# Generated by Django 4.0.5 on 2022-07-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reclutadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_r', models.CharField(max_length=40)),
                ('apellido_r', models.CharField(max_length=40)),
                ('DNI_r', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(max_length=40)),
                ('turno', models.CharField(max_length=40)),
                ('modalidad', models.CharField(max_length=40)),
            ],
        ),
    ]
