# Generated by Django 4.0.5 on 2022-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclutadores',
            old_name='DNI_r',
            new_name='DNI',
        ),
        migrations.RenameField(
            model_name='reclutadores',
            old_name='apellido_r',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='reclutadores',
            old_name='nombre_r',
            new_name='nombre',
        ),
    ]
